apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-noticias
      image: aluracursos/portal-noticias:1
      envFrom:
        - configMapRef:
            name: config-map-portal-noticias
