apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: pod-pv
      image: nginx:latest
      volumeMounts:
        - mountPath: /primeiro-pv
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc
