apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: pod-volume
      image: nginx:latest
      volumeMounts:
        - mountPath: /primeiro-volume
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /tmp
        type: Directory
