apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  selector:
    matchLabels:
      app: portal-noticias
  template:
    metadata:
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-noticias-config-map
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
  replicas: 2
