apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  labels:
    app: checkout
spec:
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: flaviogf/intensivao-microservicos-checkout
          ports:
            - containerPort: 8082
          env:
            - name: PRODUCT_URL
              value: "http://products-service:8080"
            - name: AMQP_URL
              value: "amqp://rabbitmq:rabbitmq@rabbitmq-service:5672"

---

apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: NodePort
  selector:
    app: checkout
  ports:
    - port: 8082
