apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-payment-deployment
  labels:
    app: order-payment
spec:
  selector:
    matchLabels:
      app: order-payment
  template:
    metadata:
      labels:
        app: order-payment
    spec:
      containers:
        - name: order-payment
          image: flaviogf/intensivao-microservicos-order
          env:
            - name: AMQP_URL
              value: "amqp://rabbitmq:rabbitmq@rabbitmq-service:5672"
            - name: REDIS_URL
              value: redis-service:6379
          command: ["./order"]
          args: ["-o", "payment"]
