version: '3.9'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/local/app
    env_file:
      - .env/development/database
      - .env/development/web
    depends_on:
      - redis
      - database
  redis:
    image: redis
  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
