version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
